DROP TABLE sphere CASCADE;
DROP TABLE organization CASCADE;
DROP TABLE sphere_organization CASCADE;
DROP TABLE distance CASCADE;
DROP TABLE incident CASCADE;
DROP TABLE reason CASCADE;
DROP TABLE unpleasant_word CASCADE;
DROP TABLE action_with_word CASCADE;
DROP TABLE field CASCADE;
DROP TABLE action_owner CASCADE;
DROP TABLE field_action CASCADE;
DROP TYPE argumentation;