@startuml

class Scratch
class Aeroblast
class Blizzard
class Octazooka
class ThunderShock
class LightScreen
class Minimize
class SleepTalk
class Substitute
class ThunderWave

class Moves
class PhysicalMoves
class SpecialMoves
class StatusMoves

class Pokemons
class Claydol
class Electabuzz
class Magnemite
class Magneton
class Pinsir
class Slowbro

class Main

Scratch       -[#000082,plain]-^  PhysicalMoves

Aeroblast     -[#000082,plain]-^  SpecialMoves
Blizzard      -[#000082,plain]-^  SpecialMoves
Octazooka     -[#000082,plain]-^  SpecialMoves
ThunderShock  -[#000082,plain]-^  SpecialMoves

LightScreen   -[#000082,plain]-^  StatusMoves
Minimize      -[#000082,plain]-^  StatusMoves
SleepTalk     -[#000082,plain]-^  StatusMoves
Substitute    -[#000082,plain]-^  StatusMoves
ThunderWave   -[#000082,plain]-^  StatusMoves

StatusMoves   -[#000082,plain]-^  Moves
DamageMoves   -[#000082,plain]-^  Moves
PhysicalMoves -[#000082,plain]-^  DamageMoves
SpecialMoves  -[#000082,plain]-^  DamageMoves

Claydol       -[#000082,plain]-^  Pokemons
Magneton      -[#000082,plain]-^  Claydol
Magnemite     -[#000082,plain]-^  Magneton

Pinsir        -[#000082,plain]-^  Pokemons
Electabuzz    -[#000082,plain]-^  Pinsir

Slowbro       -[#000082,plain]-^  Pokemons

@enduml