#!/bin/bash

# Compile java file to java class
javac Main.java

# Create jar file
jar cvf Main.jar *.class

# Now we need to create our MANIFEST.MF
touch MANIFEST.MF
echo "Main-Class: Main" >> MANIFEST.MF

# And lets replace automaticaly created MANIFEST.MF by our MANIFEST.MF
jar uvfm Main.jar MANIFEST.MF
