
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA FALSE LBRACE LBRACKET NULL NUMBER RBRACE RBRACKET STRING TRUEdataset : object\n               | arrayobject : LBRACE members RBRACEmembers : pair\n               | pair COMMA memberspair : STRING COLON valuearray : LBRACKET elements RBRACKETelements :\n                | value\n                | value COMMA elementsvalue : STRING\n             | NUMBER\n             | object\n             | array\n             | TRUE\n             | FALSE\n             | NULL'
    
_lr_action_items = {'LBRACE':([0,5,20,22,],[4,4,4,4,]),'LBRACKET':([0,5,20,22,],[5,5,5,5,]),'$end':([1,2,3,18,21,],[0,-1,-2,-3,-7,]),'STRING':([4,5,19,20,22,],[8,11,8,11,11,]),'RBRACKET':([5,9,10,11,12,13,14,15,16,17,18,21,22,25,],[-8,21,-9,-11,-12,-13,-14,-15,-16,-17,-3,-7,-8,-10,]),'NUMBER':([5,20,22,],[12,12,12,]),'TRUE':([5,20,22,],[15,15,15,]),'FALSE':([5,20,22,],[16,16,16,]),'NULL':([5,20,22,],[17,17,17,]),'RBRACE':([6,7,11,12,13,14,15,16,17,18,21,23,24,],[18,-4,-11,-12,-13,-14,-15,-16,-17,-3,-7,-5,-6,]),'COMMA':([7,10,11,12,13,14,15,16,17,18,21,24,],[19,22,-11,-12,-13,-14,-15,-16,-17,-3,-7,-6,]),'COLON':([8,],[20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'dataset':([0,],[1,]),'object':([0,5,20,22,],[2,13,13,13,]),'array':([0,5,20,22,],[3,14,14,14,]),'members':([4,19,],[6,23,]),'pair':([4,19,],[7,7,]),'elements':([5,22,],[9,25,]),'value':([5,20,22,],[10,24,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> dataset","S'",1,None,None,None),
  ('dataset -> object','dataset',1,'p_dataset','add3.py',40),
  ('dataset -> array','dataset',1,'p_dataset','add3.py',41),
  ('object -> LBRACE members RBRACE','object',3,'p_object','add3.py',45),
  ('members -> pair','members',1,'p_members','add3.py',49),
  ('members -> pair COMMA members','members',3,'p_members','add3.py',50),
  ('pair -> STRING COLON value','pair',3,'p_pair','add3.py',57),
  ('array -> LBRACKET elements RBRACKET','array',3,'p_array','add3.py',62),
  ('elements -> <empty>','elements',0,'p_elements','add3.py',66),
  ('elements -> value','elements',1,'p_elements','add3.py',67),
  ('elements -> value COMMA elements','elements',3,'p_elements','add3.py',68),
  ('value -> STRING','value',1,'p_value','add3.py',77),
  ('value -> NUMBER','value',1,'p_value','add3.py',78),
  ('value -> object','value',1,'p_value','add3.py',79),
  ('value -> array','value',1,'p_value','add3.py',80),
  ('value -> TRUE','value',1,'p_value','add3.py',81),
  ('value -> FALSE','value',1,'p_value','add3.py',82),
  ('value -> NULL','value',1,'p_value','add3.py',83),
]
